# -*- coding: utf-8 -*-
"""Naive Bayes-223040145

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z9RufKt-EQXB44vb5gse74yFCNq3J8IZ

# **Naive Bayes untuk data turis belanja**
"""

from google.colab import files

uploaded = files.upload()  # Ini akan membuka jendela unggahan file

import pandas as pd

# Dapatkan nama file yang diunggah (mengambil kunci dari dictionary `uploaded`)
file_name = list(uploaded.keys())[0]

# Membaca CSV ke dalam DataFrame
df = pd.read_csv(file_name, sep=';')

# Menampilkan beberapa baris pertama untuk verifikasi
print(df.head())

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB  # Menggunakan GaussianNB untuk data numerik
from sklearn.metrics import accuracy_score, classification_report

# Mendefinisikan x dan y
X = df.drop('Purchased', axis=1)
y = df['Purchased']

print("data X:/n", X,"/n")
print("data Y:/n",y, "/n")

# Bagi data menjadi training dan testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Inisialisasi model Naïve Bayes (GaussianNB)
model = GaussianNB()

# Latih model menggunakan data training
print("X train :")
print(X_train, "/n")
print("y train :")
print(y_train,"/n")
model.fit(X_train, y_train)

# Lakukan prediksi pada data testing
print("X Test ")
print(X_test,"/n")
print(" y Test :")
print(y_test,"/n")
y_pred = model.predict(X_test)

# Evaluasi performa model
accuracy = accuracy_score(y_test, y_pred)
print(f"Akurasi: {accuracy}")

print(classification_report(y_test, y_pred))