# -*- coding: utf-8 -*-
"""Testpraktek-KMeans_M1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sD3u8Il7mjmX17NxftOeyUa5q__yLvAZ
"""

import pandas as pd
import numpy as np

train = np.array([['Nilai Matematika','Nilai Bahasa Inggris'],
[85, 78],
[70, 91],
[55, 60],
[90, 85],
[65, 70],
[75, 80],
[80, 75],
[50, 65],
[95, 90],
[62, 72],
[78, 82],
[68, 73],
[88, 79],
[73, 67],
[58, 63],
[82, 88],
[67, 75],
[91, 87],
[60, 68],
[85, 81]
])

train = pd.DataFrame(train)

from sklearn.cluster import KMeans

mykmeans = KMeans(n_clusters=2)

train



train.columns=train.iloc[0]

train.drop([0],axis=0,inplace=True)

train

mykmeans.fit(train)

mykmeans.cluster_centers_

mykmeans.labels_

mykmeans.n_iter_

mykmeans.inertia_

train2 = np.array([['Nilai Matematika','Nilai Bahasa Inggris'],
[85, 78],
[70, 91],
[55, 60],
[90, 85],
[65, 70],
[75, 80],
[80, 75],
[50, 65],
[95, 90],
[62, 72],
[78, 82],
[68, 73],
[88, 79],
[73, 67],
[58, 63],
[82, 88],
[67, 75],
[91, 87],
[60, 68],
[85, 81]
])

train2 = pd.DataFrame(train2)

train2.columns=train2.iloc[0]

train2.drop([0],axis=0,inplace=True)

"""# New Section"""

train2

from sklearn.cluster import KMeans

kmeans2 = KMeans(n_clusters=2)

kmeans2.fit(train2)

kmeans2.cluster_centers_

kmeans2.inertia_

kmeans2.n_iter_

kmeans2.labels_

train3 = np.array([['Nilai Matematika','Nilai Bahasa Inggris'],
[85, 78],
[70, 91],
[55, 60],
[90, 85],
[65, 70],
[75, 80],
[80, 75],
[50, 65],
[95, 90],
[62, 72],
[78, 82],
[68, 73],
[88, 79],
[73, 67],
[58, 63],
[82, 88],
[67, 75],
[91, 87],
[60, 68],
[85, 81]
])

train3 = pd.DataFrame(train3)

train3.columns=train3.iloc[0]

train3.columns

train3.drop([0],axis=0,inplace=True)

train3

from sklearn.cluster import KMeans

kmeans3 = KMeans(n_clusters=2)

kmeans3.fit(train3)

kmeans3.cluster_centers_

kmeans3.labels_

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from IPython import display
# %matplotlib inline

from sklearn.decomposition import PCA
mypca = PCA(n_components=2)
train3_pca = mypca.fit_transform(train3)

train3_pca

kmeans3_pca = KMeans(n_clusters=2)

kmeans3_pca.fit(train3_pca)

kmeans3_pca.cluster_centers_

kmeans3.labels_

plt.scatter(train3_pca[:, 0], train3_pca[:, 1],c=kmeans3_pca.labels_,cmap='rainbow')

from sklearn.decomposition import PCA
pca = PCA(n_components=1)
train4_pca = pca.fit_transform(train3)

train4_pca

kmeans4_pca = KMeans(n_clusters=2)

kmeans4_pca.fit(train4_pca)

kmeans4_pca.inertia_

kmeans4_pca.cluster_centers_

kmeans4_pca.labels_

kmeans4_pca= KMeans(n_clusters=3)

kmeans4_pca.fit(train4_pca)

kmeans4_pca.cluster_centers_

kmeans4_pca.labels_

train4_pca

kmeans4_pca.inertia_

